name: Test Cognate on Debian
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./SETUP.debian
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./TEST
      - name: Upload test output
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: tests-debian
          path: tests/*
