name: Test Cognate features
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./SETUP.debian
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./TEST
      - name: Upload tests
        uses: actions/upload-artifact@v1
        with:
          name: debian test log
          path: test.log
  test-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./SETUP.macos
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./TEST
      - name: Upload tests
        uses: actions/upload-artifact@v1
        with:
          name: macos test log
          path: test.log
