name: Test Cognate features
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./SETUP > /dev/null 2>&1
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./TEST
