name: Test Cognate features
jobs:
  test-debian:
    runs-on: ubuntu-latest
    on:
      push:
        branches: [ master ]
      pull_request:
        branches: [ master ]
      workflow_dispatch:
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./SETUP.debian
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./TEST
      - name: Upload test output
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: tests-debian
          path: tests/*.log
  test-macos:
    runs-on: macOS-latest
    on:
      workflow_dispatch:
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./SETUP.macos
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          ./TEST
      - name: Upload test output
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: tests-macOS
          path: tests/*.log
